### ISSUE TITLE
Usage question v2

### ISSUE THREAD

**Issue by rokaslit6** [saintsweeto/hunterio#7]
Hi, an awesome wrapper you got here & thanks for the recent update.

Having said that, I'm having trouble getting a good response from Hunter. I always get an empty response when trying to do searchDomain & I hope you could help me out as maybe other newbies might find this useful.

I have a function in my controller that looks like this (my-api-key is set):
```
public function hunterDS(Request $request) {
        $domains = preg_split('/\\s/', $request->input('domain'));
        $hunter = new Hunter('my-api-key');
        $hunter->searchDomain($domains, ['limit' => 5]);
        dd($hunter);
}
```
dd($hunter) dumps this:
<img width="241" alt="Screen Shot 2019-12-12 at 3 05 31 PM" src="https://user-images.githubusercontent.com/30793715/70714514-f6689800-1cf0-11ea-83d6-4e66a27baf69.png">

As you can notice there's no "domain" key in this query but I can see the requested domain in the browser URI.

Am I adding my api key the correct way or should it be added somewhere in hunter.php?

@saintsweeto

**Comment by saintsweeto** [comment]
You've closed this, you might have resolved this already but for others:

1. Your API key should be real valid API key
2. First parameter should be a string and not an array
3. Make sure your passing No. 2 correctly

**Comment by rokaslit6** [comment]
I’ve closed this issue because I figured out that I was adding the api key correctly and I thought that’s the correct way of going about this since that was basically my question there. But:

2. Right so I should convert every $domains array element to a separate string & only then pass it to the request. I will try that.

3. By No. 2 do you mean the limits param?

Thanks!

**Comment by rokaslit6** [comment]
Just wanted to drop a quick douce that yeah, my problem was solved with a simple foreach loop for $domains.
